### PR TITLE
Form utilisation

### PR DESCRIPTION
**Pull request by fixel99**
Started working on the form and how it behaves. At this stage, it will probably just be a design element and not be functional, however if I have enough time I guess I could do some php coding and make it usable.

### CODE REVIEW

**Comment by fixel99** [comment]
Don't think there's much else todo here. @russmaxdesign can you take a quick look?

**Comment by russmaxdesign** [comment]
👍 

Looks good. I just tested two messages - the first a valid one, the second with three deliberate fails and all of them were as expected:

- check to see if form can be submitted with invalid email address
- check to see if form can be submitted with no name
- check to see if form can be submitted with no comment

All tests worked - meaning the form could not be submitted - so this is good.

Did you receive the two tests submissions?

**Comment by russmaxdesign** [comment]
One side note - not critical for this site but worth being aware of.

The error message is a modal popup - which is very clear and obvious for sighted users. For some users, however, this is not as good as the option where you flag each field that need changing - actually adding the error message directly below or beside the field in question.

Again, not critical here, but it is "best practice"

**Comment by fixel99** [comment]
I didn't receive anything as it is not set up to actually do so mething behind the scenes. As per your second point: I was going to but it seemed like quite a lot of effort for what will probably not even be marked (in addition to having to change the current validation system). But again, if I have time I will look back into it and modify it. Thanks for taking a look!

**Pull request merged**
